### ISSUE TITLE
Non health state deterministic startup

### ISSUE THREAD

**Issue by mattackerman808** [polaris-gslb/polaris-gslb#51]
I am attempting to fix this on my own, however I thought I would report it as well in case you have some ideas on how to fix it.

Here is the situation:

In order to invoke a config change polaris-health must be restarted. On restart it pushes a distribution table with everything marked UP. Only when a probe comes back unhealthy does it toggle it DOWN.

This is causing an issue as DNS traffic is getting sent to unhealthy nodes while the process gathers endpoint health and brings them offline.

The request is to either pull state from memcached (if available) on startup or provide a control/gaurdian command to just reload the config without reseting all state. Both would be absolutely ideal.

This would also be a performance boost to startup as currently the system is writing lots of 'unneeded' state changes to memcached.

**Comment by mattackerman808** [comment]
Looking this over a little more, it appears the issue may be related to the retry counters. End points are marked health until the retry expires again.

**Comment by antongavrik** [comment]
Good catch. We could make it so that, on a start-up, no state push is performed until health status of all members has been determined. This will delay the initial push by up to max configured timeout*retries. Thoughts?

**Comment by mattackerman808** [comment]
I think that is a good middle ground. If memcached is already warm then it will have no impact. Better to send SERVFAILs then send traffic to a down endpoint.

I haven't had much time to look into this, let me know if you think it's an easy fix.

**Comment by antongavrik** [comment]
When Polaris starts, any pool member status change may (depending on the combination of internal timers) cause generic/ppdns states carrying partially default, non-initialized values to be propagated to memcached. Based on the fallback methods assigned, this may cause Polaris, for a short time, until the health state convergence is complete, to either return IP addresses of unhealthy endpoints (when fallback is set to any) or refuse to answer the query (when fallback is set to refuse). A slow start, health state deterministic startup procedure needs to be implemented so that the initial states push is only performed after the health status of every pool member is fully determined.

**Comment by antongavrik** [comment]
I have a fix in https://github.com/polaris-gslb/polaris-gslb/tree/slowstart in case you wanted to test and let me know if it resolves the issue for you.

**Comment by mattackerman808** [comment]
The fix works great. I have been testing it for awhile and it solves the problem.
